// src/services/agent.js
import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const SYSTEM_PROMPT = `You are a trading analyst generating candidate trade proposals for a paper-trading platform.

The user has NOT specified a request. Your job is to analyze current market conditions
and propose 0 to 3 trades worth considering.

STRICT RULES:
- Respond ONLY with valid JSON. No prose, no markdown fences.
- Shape:
  {
    "proposals": [
      {
        "action": "BUY" | "SELL",
        "symbol": "GOLD" | "SILVER" | "COPPER" | "OIL" | "BTC",
        "quantity": number,
        "orderType": "MARKET" | "LIMIT",
        "limitPrice": number | null,
        "reasoning": string
      }
    ]
  }
- If market conditions do not justify a proposal, return {"proposals": []}.
- Max notional per trade: $50 (paper trading).
- Reasoning must be factual and reference the instrument's actual characteristics,
  not invented price levels or news.
- Never mention returns, profit projections, or guaranteed outcomes.`;

export async function generateScheduledProposals({ userId }) {
  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-5",
    max_tokens: 1500,
    system: SYSTEM_PROMPT,
    messages: [{
      role: "user",
      content: "Generate today's candidate proposals."
    }]
  });

  const text = response.content[0].text.trim();

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    console.error("[AGENT] Non-JSON response:", text.slice(0, 200));
    return [];
  }

  if (!Array.isArray(parsed.proposals)) return [];

  return parsed.proposals.filter(validateProposal).slice(0, 3);
}

function validateProposal(p) {
  if (!p || typeof p !== "object") return false;
  if (!["BUY", "SELL"].includes(p.action)) return false;
  if (!["GOLD", "SILVER", "COPPER", "OIL", "BTC"].includes(p.symbol)) return false;
  if (typeof p.quantity !== "number" || p.quantity <= 0 || p.quantity > 100) return false;
  if (!["MARKET", "LIMIT"].includes(p.orderType)) return false;
  if (p.orderType === "LIMIT" && (typeof p.limitPrice !== "number" || p.limitPrice <= 0)) return false;
  if (typeof p.reasoning !== "string" || p.reasoning.length === 0) return false;
  return true;
}

// Supported instruments — kept small for the mock
const INSTRUMENTS = {
  GOLD:   { basePrice: 2650, volatility: 0.015 },
  SILVER: { basePrice: 31,   volatility: 0.025 },
  COPPER: { basePrice: 4.2,  volatility: 0.020 },
  OIL:    { basePrice: 78,   volatility: 0.030 },
  BTC:    { basePrice: 62000, volatility: 0.040 }
};

function pickInstrument(prompt) {
  const upper = prompt.toUpperCase();
  for (const symbol of Object.keys(INSTRUMENTS)) {
    if (upper.includes(symbol)) return symbol;
  }
  // Default to gold if the prompt doesn't name one
  return "GOLD";
}

function decideAction(prompt) {
  const lower = prompt.toLowerCase();
  if (lower.includes("sell") || lower.includes("short")) return "SELL";
  return "BUY";
}

function calculateQuantity(symbol, notional = 20) {
  // Position size roughly $20 notional for paper trading
  const price = INSTRUMENTS[symbol].basePrice;
  const raw = notional / price;
  // Round to a sane precision
  return Math.max(0.0001, Math.round(raw * 10000) / 10000);
}

function buildReasoning(symbol, action, prompt) {
  return [
    `Mock agent analysis for: "${prompt}"`,
    `Instrument: ${symbol}`,
    `Direction: ${action}`,
    `Rationale: Simulated signal based on instrument recognition.`,
    `Note: This is a paper-trading proposal generated by the mock agent.`
  ].join("\n");
}

/**
 * Generates a trade proposal. Does NOT execute anything.
 * Returns an object shaped to match the `proposals` table.
 */
export async function generateProposal({ userId, prompt }) {
  const symbol = pickInstrument(prompt);
  const action = decideAction(prompt);
  const quantity = calculateQuantity(symbol);
  const orderType = "MARKET";
  const limitPrice = null;
  const reasoning = buildReasoning(symbol, action, prompt);

  return {
    action,
    symbol,
    quantity,
    orderType,
    limitPrice,
    reasoning
  };
}

/**
 * Executes an approved trade in the user's sandbox.
 * For now this is a mock execution — logs the intent and returns a fake fill.
 * Later this delegates to the sandbox provisioning layer.
 */
export async function executeTrade({ userId, proposal }) {
  const price = INSTRUMENTS[proposal.symbol]?.basePrice ?? 0;
  const fillPrice = price * (1 + (Math.random() - 0.5) * 0.002); // ±0.1% slippage

  return {
    status: "FILLED",
    symbol: proposal.symbol,
    action: proposal.action,
    quantity: proposal.quantity,
    fillPrice: Number(fillPrice.toFixed(4)),
    notional: Number((fillPrice * proposal.quantity).toFixed(2)),
    executedAt: new Date().toISOString(),
    venue: "paper",
    note: "Mock fill — no real order placed."
  };
}
