// src/services/agent.js

// Supported instruments — kept small for the mock
const INSTRUMENTS = {
  GOLD:   { basePrice: 2650, volatility: 0.015 },
  SILVER: { basePrice: 31,   volatility: 0.025 },
  COPPER: { basePrice: 4.2,  volatility: 0.020 },
  OIL:    { basePrice: 78,   volatility: 0.030 },
  BTC:    { basePrice: 62000, volatility: 0.040 }
};

function pickInstrument(prompt) {
  const upper = prompt.toUpperCase();
  for (const symbol of Object.keys(INSTRUMENTS)) {
    if (upper.includes(symbol)) return symbol;
  }
  // Default to gold if the prompt doesn't name one
  return "GOLD";
}

function decideAction(prompt) {
  const lower = prompt.toLowerCase();
  if (lower.includes("sell") || lower.includes("short")) return "SELL";
  return "BUY";
}

function calculateQuantity(symbol, notional = 20) {
  // Position size roughly $20 notional for paper trading
  const price = INSTRUMENTS[symbol].basePrice;
  const raw = notional / price;
  // Round to a sane precision
  return Math.max(0.0001, Math.round(raw * 10000) / 10000);
}

function buildReasoning(symbol, action, prompt) {
  return [
    `Mock agent analysis for: "${prompt}"`,
    `Instrument: ${symbol}`,
    `Direction: ${action}`,
    `Rationale: Simulated signal based on instrument recognition.`,
    `Note: This is a paper-trading proposal generated by the mock agent.`
  ].join("\n");
}

/**
 * Generates a trade proposal. Does NOT execute anything.
 * Returns an object shaped to match the `proposals` table.
 */
export async function generateProposal({ userId, prompt }) {
  const symbol = pickInstrument(prompt);
  const action = decideAction(prompt);
  const quantity = calculateQuantity(symbol);
  const orderType = "MARKET";
  const limitPrice = null;
  const reasoning = buildReasoning(symbol, action, prompt);

  return {
    action,
    symbol,
    quantity,
    orderType,
    limitPrice,
    reasoning
  };
}

/**
 * Executes an approved trade in the user's sandbox.
 * For now this is a mock execution — logs the intent and returns a fake fill.
 * Later this delegates to the sandbox provisioning layer.
 */
export async function executeTrade({ userId, proposal }) {
  const price = INSTRUMENTS[proposal.symbol]?.basePrice ?? 0;
  const fillPrice = price * (1 + (Math.random() - 0.5) * 0.002); // ±0.1% slippage

  return {
    status: "FILLED",
    symbol: proposal.symbol,
    action: proposal.action,
    quantity: proposal.quantity,
    fillPrice: Number(fillPrice.toFixed(4)),
    notional: Number((fillPrice * proposal.quantity).toFixed(2)),
    executedAt: new Date().toISOString(),
    venue: "paper",
    note: "Mock fill — no real order placed."
  };
}
